#!/bin/bash -e
###############################################################################
#
# Copyright 2022 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################

cd ${0%*/*}

# if [ ! -e Dockerfile ]; then
# 	echo "ERROR: Dockerfile is missing."
# 	exit 1
# fi

if ! (which wget > /dev/null 2>&1); then
	echo "wget is required to build BFB"
	exit 1
fi

if ! (which docker > /dev/null 2>&1); then
	echo "docker is required to build BFB"
	exit 1
fi

DISTRO="oraclelinux"
DISTRO_VERSION="8"
DOCA_VERSION="2.7.0"
BSP_VERSION="4.7.1-13167"
BF_VERSION=${BSP_VERSION%-*}
IMAGE_TYPE=${IMAGE_TYPE:-"prod"}
RELTARGET="24.04"
BUILDVER=${BUILDVER:-"16"}

WDIR=/tmp/${DISTRO}${DISTRO_VERSION}.$$
BASE_URL=${BASE_URL:-"https://linux.mellanox.com/public/repo"}

mkdir -p $WDIR

mkdir -p $WDIR/bootimages
wget -P $WDIR/bootimages -r --no-verbose --no-directories -l1 --no-parent -A 'mlxbf-bootimages*.aarch64.rpm' ${BASE_URL}/bluefield/${BSP_VERSION}/bootimages/${IMAGE_TYPE}/

mkdir -p $WDIR/uek
if [ -d uek ]; then
	cp -a uek $WDIR
else
	wget -P $WDIR/uek -r --no-verbose --no-directories -l1 --no-parent -A 'kernel*aarch64.rpm' ${BASE_URL}/doca/${DOCA_VERSION}/OracleLinux8/uek7/aarch64/
fi

cp	Dockerfile.* \
	create_bfb \
	install.sh \
	build_ol_bfb \
	run_create_bfb \
	docker-ce.repo \
	../../common/tools/qemu-aarch64-static \
	$WDIR

if [ -d uek ]; then
	cp -a uek $WDIR
fi

build_rpms=${build_rpms:-0}
BUILDNUM=${BUILDNUM:-"1.inbox"}

cd $WDIR

docker_image=bfb_runtime_${DISTRO,,}${DISTRO_VERSION,,}

docker rm -f BlueField_OS_${DISTRO}_${DISTRO_VERSION} 2> /dev/null || true

if [ $build_rpms -eq 1 ]; then
	sed -e "s/@DISTRO_VERSION@/${DISTRO_VERSION}/g" \
		-e "s/@IMAGE_TYPE@/${IMAGE_TYPE}/g" \
		-e "s/@CUSTOM_VERSION@/$CUSTOM_VERSION/" \
		-e "s/@BF_VERSION@/${BF_VERSION}/g" \
		-e "s/@BSP_VERSION@/${BSP_VERSION}/g" \
		-e "s/@BUILDVER@/${BUILDVER}/g" \
		Dockerfile.build > $WDIR/Dockerfile

	docker build -t bfb_build_${DISTRO}${DISTRO_VERSION} -f Dockerfile .
	docker run -t --rm --privileged -e container=docker \
		-v $PWD:/workspace \
		--name BlueField_OS_${DISTRO}_${DISTRO_VERSION} \
		--mount type=bind,source=/dev,target=/dev \
		--mount type=bind,source=/sys,target=/sys \
		--mount type=bind,source=/proc,target=/proc \
		bfb_build_${DISTRO}${DISTRO_VERSION}

    /bin/rm -f *debug*.rpm

    mkdir -p $WDIR/SoC
    mv *.rpm $WDIR/SoC
fi

sed -e "s/@DISTRO_VERSION@/${DISTRO_VERSION}/g" \
	-e "s/@IMAGE_TYPE@/${IMAGE_TYPE}/g" \
	-e "s/@CUSTOM_VERSION@/${CUSTOM_VERSION}/g" \
	-e "s/@BSP_VERSION@/${BSP_VERSION}/g" \
	-e "s/@DOCA_VERSION@/${DOCA_VERSION}/g" \
	-e "s/@BF_VERSION@/${BF_VERSION}/g" \
	-e "s|@BASE_URL@|${BASE_URL}|g" \
	-e "s/@BUILDVER@/${BUILDVER}/g" \
	-e "s/@RELTARGET@/${RELTARGET}/g" \
	Dockerfile.run > $WDIR/Dockerfile

docker build -t ${docker_image} \
	--build-arg BASE_URL=$BASE_URL \
	--build-arg DOCA_VERSION=$DOCA_VERSION \
	--build-arg BSP_VERSION=$BSP_VERSION \
	-f Dockerfile .

docker run -t --rm --privileged -e container=docker \
	-v $PWD:/workspace \
	--name BlueField_OS_${DISTRO}_${DISTRO_VERSION} \
	--mount type=bind,source=/dev,target=/dev \
	--mount type=bind,source=/sys,target=/sys \
	--mount type=bind,source=/proc,target=/proc \
	${docker_image}

readlink -f *.bfb

echo "Default root password is: oracle"
