#!/bin/bash -x

if [ -d /root/workspace/SoC/ ]; then
	rpm -ihv --nodeps /root/workspace/SoC/*.rpm
fi

bfb_name=$(cat /etc/mlnx-release)
BMC_URL="https://linux.mellanox.com/public/repo/bluefield/BMC/BF3"

# Restore bfb name
echo $bfb_name > /etc/mlnx-release

for bootimage in /root/workspace/bootimages/*.rpm
do
    current_type=$(cat /etc/mlnx-release | grep -oE "unsigned|dev|prod")
	echo "Current type: $current_type"
	case "$bootimage" in
	*signed*)
		type=prod
		/bin/rm -f /workspace/BF3BMC/bmc/*
		/bin/rm -f /workspace/BF3BMC/cec/*
		/bin/rm -f /workspace/BF3BMC/golden_images/dpu/*
		wget -P /workspace/BF3BMC/bmc -q --no-check-certificate ${BMC_URL}/bmc/24.04-4/bf3-bmc-24.04-4_opn.fwpkg
		wget -P /workspace/BF3BMC/cec -q --no-check-certificate ${BMC_URL}/cec/00.02.0182.0000/cec1736-ecfw-00.02.0182.0000-n02-rel-prod.fwpkg
		wget -P /workspace/BF3BMC/golden_images/dpu -q --no-check-certificate ${BMC_URL}/golden_images/dpu/4.7.0-13101/BlueField-GA-4.7.0.13101_preboot-install.bfb
        wget -P /workspace/BF3BMC/golden_images/fw -q --no-check-certificate -r --no-directories -l1 --no-parent -A 'fw*bfb' ${BMC_URL}/golden_images/nic-fw/32_40_1000/
		;;
	esac

	rpm -ihv --force $bootimage
	sed -i -e "s/$current_type/$type/" /etc/mlnx-release
	/root/workspace/create_bfb -k $(/bin/ls -1 /lib/modules/ | head -1)
done
