#!/bin/bash -e
###############################################################################
#
# Copyright 2022 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################

cd ${0%*/*}

if [ ! -e Dockerfile ]; then
	echo "ERROR: Dockerfile is missing."
	exit 1
fi

if ! (which wget > /dev/null 2>&1); then
	echo "wget is required to build BFB"
	exit 1
fi

if ! (which docker > /dev/null 2>&1); then
	echo "docker is required to build BFB"
	exit 1
fi

DISTRO="centos"
DISTRO_VERSION="7.6"
DOCA_VERSION="2.7.0"
BSP_VERSION="4.7.0-13127"
MLNX_OFED_VERSION="24.01-0.6.6.0"
BF2_BMC_VERSION="24.04-5"
BF3_BMC_VERSION="24.04-5"
BF2_CEC_VERSION="04.0f"
BF3_CEC_VERSION="00.02.0182.0000"
BF3_NIC_FW_VERSION="32_41_1300"
IMAGE_TYPE=${IMAGE_TYPE:-"prod"}
CUSTOM_VERSION=${CUSTOM_VERSION:-""}
INCLUDE_BF2BMC=${INCLUDE_BF2BMC:-"yes"}
INCLUDE_BF3BMC=${INCLUDE_BF3BMC:-"yes"}
BASE_URL=${BASE_URL:-"https://linux.mellanox.com/public/repo"}

WDIR=/tmp/${DISTRO}${DISTRO_VERSION}.$$

mkdir -p $WDIR/bootimages
wget -P $WDIR/bootimages -r --no-verbose --no-directories -l1 --no-parent -A 'mlxbf-bootimages*.aarch64.rpm' ${BASE_URL}/bluefield/${BSP_VERSION}/bootimages/${IMAGE_TYPE}/

cp -a \
	Dockerfile \
	create_bfb \
	install.sh \
	install.env \
	../../common/tools/qemu-aarch64-static \
	../../common/packages/parted-3.2-39.el7.aarch64.rpm \
	$WDIR

cd $WDIR

if [ "${INCLUDE_BF2BMC}" == "yes" ]; then
	mkdir -p BF2BMC/pk/{bmc,cec} BF2BMC/qp
	echo "Downloading BlueField-2 BMC software..."
	wget -q -P $WDIR/BF2BMC/pk/bmc -r --no-verbose --no-directories -l1 --no-parent -A 'bf2-bmc*tar' ${BASE_URL}/bluefield/BMC/BF2/bmc/${BF2_BMC_VERSION}/
	wget -q -P $WDIR/BF2BMC/pk/cec -r --no-verbose --no-directories -l1 --no-parent -A 'cec*bin' ${BASE_URL}/bluefield/BMC/BF2/cec/${BF2_CEC_VERSION}/
fi

if [ "${INCLUDE_BF3BMC}" == "yes" ]; then
	mkdir -p BF3BMC/pk/{bmc,cec,golden_images/dpu,golden_images/fw} BF3BMC/{dk,qp}
	echo "Downloading BlueField-3 BMC software..."
	wget -q -P $WDIR/BF3BMC/pk/bmc -r --no-verbose --no-directories -l1 --no-parent -A 'bf3-bmc*fwpkg' ${BASE_URL}/bluefield/BMC/BF3/bmc/${BF3_BMC_VERSION}/
	wget -q -P $WDIR/BF3BMC/pk/cec -r --no-verbose --no-directories -l1 --no-parent -A 'cec*fwpkg' ${BASE_URL}/bluefield/BMC/BF3/cec/${BF3_CEC_VERSION}/
	wget -q -P $WDIR/BF3BMC/pk/golden_images/dpu -r --no-verbose --no-directories -l1 --no-parent -A 'BlueField*.bfb' ${BASE_URL}/bluefield/BMC/BF3/golden_images/dpu/${BSP_VERSION}/
	wget -q -P $WDIR/BF3BMC/pk/golden_images/fw -r --no-verbose --no-directories -l1 --no-parent -A 'fw*.bfb' ${BASE_URL}/bluefield/BMC/BF3/golden_images/nic-fw/${BF3_NIC_FW_VERSION}/
fi

docker_image=bfb_runtime_${DISTRO,,}${DISTRO_VERSION,,}

sed -i -e "s/@IMAGE_TYPE@/$IMAGE_TYPE/g;s/@CUSTOM_VERSION@/$CUSTOM_VERSION/g" \
    -e "s,@BASE_URL@,$BASE_URL,g" \
    -e "s/@DOCA_VERSION@/$DOCA_VERSION/g" Dockerfile

docker build -t ${docker_image} \
	--build-arg BASE_URL=$BASE_URL \
	--build-arg DOCA_VERSION=$DOCA_VERSION \
	--build-arg BSP_VERSION=$BSP_VERSION \
	--build-arg DISTRO=$DISTRO \
	--build-arg DISTRO_VERSION=$DISTRO_VERSION \
	-f Dockerfile .

docker run -t --rm --privileged -e container=docker \
	-v $PWD:/workspace \
	--name BlueField_OS_${DISTRO}_${DISTRO_VERSION} \
	--mount type=bind,source=/dev,target=/dev \
	--mount type=bind,source=/sys,target=/sys \
	--mount type=bind,source=/proc,target=/proc \
	${docker_image}

readlink -f *.bfb

echo "Default root password is: centos"
