#!/bin/bash

usage()
{
	cat << EOF
IMAGE_TYPE=<prod|dev> `basename $0` <Distro> <version>

E.g.:
	IMAGE_TYPE=prod `basename $0` ubuntu 20.04

Supported Distros:
`/bin/ls -1 */*/bfb-build | xargs dirname | tr -s '/' ' '`
EOF
}

case "$1" in
	-h|--help)
		usage
		exit 0
		;;
esac

if [ ! -x $1/$2/bfb-build ]; then
	echo "ERROR: Distribution $1$2 is not supported"
	exit 1
fi

IMAGE_TYPE=${IMAGE_TYPE:-"prod"}
CUSTOM_VERSION=${CUSTOM_VERSION:-".$(date +%Y%m%d)"}

if [ "`uname -m`" != "aarch64" ]; then
	if [ ! -d /etc/binfmt.d ]; then
		echo "ERROR: systemd package is required"
		exit 1
	fi
	if ! (grep -q /usr/bin/qemu-aarch64-static /etc/binfmt.d/qemu-aarch64.conf > /dev/null 2>&1); then
		cat > /etc/binfmt.d/qemu-aarch64.conf << EOF
:qemu-aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7:\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff:/usr/bin/qemu-aarch64-static:
EOF
		systemctl restart systemd-binfmt
	fi
fi

IMAGE_TYPE=$IMAGE_TYPE CUSTOM_VERSION=$CUSTOM_VERSION $1/$2/bfb-build
