#!/bin/bash

###############################################################################
#
# Copyright 2023 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################

set -e

LANG=C
SDIR="/root/workspace"
kernel=$(/bin/ls -1 /lib/modules/ | head -1)

WDIR=${WDIR:-/root/workspace/bfb}

echo "Work directory: $WDIR"

PATH=$PATH:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/mellanox/scripts:/opt/mellanox/scripts/bin

/bin/rm -rf ${WDIR}
mkdir -p ${WDIR}
cd ${WDIR}
/bin/rm -rf initramfs

initramfs=$WDIR/dump-initramfs-v0

for mod in mlxbf-bootctl sdhci-of-dwcmshc mlxbf_tmfifo dw_mmc_bluefield mmc_block virtio_console mlx5_core mlx5_ib mlxfw ib_umad nvme gpio-mlxbf3 mlxbf-gige pinctrl-mlxbf3 8021q vitesse
do
    if (modinfo -k $kernel $mod 2>/dev/null | grep "filename:" | grep -q builtin); then
        continue
    fi
    if ! (modinfo -k $kernel $mod 2>/dev/null); then
        continue
    fi
    ADD_DRIVERS="$ADD_DRIVERS $mod"
done

dracut --no-hostonly -m "bash network base systemd systemd-initrd dracut-systemd shutdown udev-rules dm" \
	--install "/usr/lib/udev/rules.d/91-tmfifo_net.rules /lib/udev/rules.d/92-oob_net.rules" \
	--add-drivers "${ADD_DRIVERS}" \
	--filesystems "xfs vfat" --gzip $initramfs ${kernel}

rm -f /etc/udev/rules.d/91-tmfifo_net.rules /etc/udev/rules.d/92-oob_net.rules

cat > /etc/default/grub << EOF
GRUB_TIMEOUT=0
GRUB_RECORDFAIL_TIMEOUT=2
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL=console
GRUB_SERIAL_COMMAND="serial --unit=1"
GRUB_CMDLINE_LINUX="crashkernel=1024M console=hvc0 console=ttyAMA0 earlycon=pl011,0x01000000 modprobe.blacklist=mlx5_core,mlx5_ib biosdevname=0"
GRUB_DISABLE_RECOVERY="true"
GRUB_TIMEOUT_STYLE=countdown
GRUB_DISABLE_OS_PROBER=false
GRUB_DISABLE_LINUX_UUID=false
EOF

case "$(file --brief --mime-type "$initramfs")" in
    "application/x-lzma")
        cat_initrd="lzcat" ;;
    "application/x-lz4")
        cat_initrd="lz4cat" ;;
    *)
        cat_initrd="zcat" ;;
esac

echo "Rebuilding $initramfs"

mkdir -p ${WDIR}/initramfs
cd initramfs
$cat_initrd "$initramfs" | cpio -i

copy_bin()
{
    if [ -e $1 ]; then
        bin=$1
    else
        bin=$(which $1 2> /dev/null)
    fi
    if [ -z "$bin" ]; then
        echo "ERROR: Cannot find $1"
        return 1
    fi
    mkdir -p .$(dirname $bin)
    if [ -e .${bin} ]; then
        /bin/rm -f .${bin}
    fi
    cp -a $bin .${bin}

    # Copy dependencies
    for lib in $(ldd $bin 2> /dev/null | grep '=>' | awk '{print $3}' | grep -v '(0x0')
    do
        if [ -e .$lib ]; then
            continue
        fi
        mkdir -p .$(dirname $lib)
        cp -a $lib .$lib
        if [ -h $lib ]; then
            tlib=$(readlink -f $lib)
            if [ ! -e .$tlib ]; then
                mkdir -p .$(dirname $tlib)
                cp $tlib .$tlib
            fi
        fi
    done
}

copy_rpm()
{
    package=$1

    if ! (rpm -q $package); then
        yum install -y $package || return
    fi

    case $package in
        chkconfig)
            for f in $(rpm -ql $package | grep -v share)
            do
                if [ -d $f ]; then
                    mkdir -p .${f}
                else
                    copy_bin $f
                fi
            done
            ;;
        *mft*)
            for f in $(rpm -ql $package | grep -vw man)
            do
                if [ -d $f ]; then
                    continue
                fi
                copy_bin $f
            done
            ;;
        *)
            for f in $(rpm -ql $package | grep -vE 'share|build-id')
            do
                if [ -d $f ]; then
                    continue
                fi
                copy_bin $f
            done
            ;;
    esac
}

# Copy the content of RPM packages
for package in mlxbf-bfscripts util-linux dosfstools e2fsprogs kmod pciutils usbutils chkconfig mft mft-oem mft-nvredfish mft-mlx5 kernel-mft kmod-kernel-mft-mlnx tar xfsprogs coreutils nvme-cli mmc-utils parted which curl openssl gawk lvm2-libs device-mapper lvm2 iputils sshpass openssh-clients findutils mokutil dhcp-client net-tools wget zip $ADDON_RPMS
do
    copy_rpm $package || true
done

# Copy tools
for tool in xz efibootmgr bash getopt hexdump mstflint lspci perl \
        lsblk shutdown systemctl strings \
        mlxbf-bootctl id grep jq hostnamectl ipcalc xxd cmp file $ADDON_TOOLS
do
    if [ -d $tool ]; then
        continue
    fi
    copy_bin $tool
done

depmod -a -b ./ $kernel
ldconfig -r ./
mkdir -p usr/share/hwdata/ bin/
cp /usr/share/hwdata/pci.ids ./usr/share/hwdata/
if [ -d /lib/firmware/swissbit/ ]; then
	mkdir -p ./lib/firmware
	cp -a /lib/firmware/swissbit/ ./lib/firmware/
fi

mkdir -p ./lib/udev/rules.d
cp /lib/udev/rules.d/82-net-setup-link.rules ./lib/udev/rules.d/82-net-setup-link.rules
mkdir -p ./etc/infiniband
cp /etc/infiniband/vf-net-link-name.sh ./etc/infiniband/vf-net-link-name.sh

mkdir -p mnt

# Remove hostname that includes docker container's id
/bin/rm -f ./etc/hostname
echo localhost > /etc/hostname

touch ./etc/fstab

mkdir -p alinux
# Tar the image
XZ_OPT="--threads=0 -9 --verbose" tar -cJp --exclude='./workspace' --exclude='./signing-local' --exclude='./signing-shared' --exclude='./var/run/docker.sock' \
 --exclude='./root/workspace' --exclude='./tmp/*' --exclude='./run/*' --exclude='./sys/*' --exclude='./proc/*' --exclude='./dev/*' --exclude='./.dockerenv' \
 --exclude='./root/rpmbuild' --exclude='./root/.rpmmacros' --exclude='./root/.bash_history' --exclude='./var/tmp/*rpm' --exclude='./bin/qemu-aarch64-static' \
 --exclude='./usr/bin/qemu-aarch64-static' --exclude='./usr/bin/qemu-arm-static' --exclude='./var/lib/yum/*' --exclude='./var/cache/yum/*' -f "./alinux/image.tar.xz" -C / .
install -m 0755 ${SDIR}/install.sh ./alinux/install.sh
cp -a ${SDIR}/install.env ./alinux/

mkdir scripts
cat > scripts/initrd-install << EOF
#!/bin/sh

echo
echo "=================================" | tee /dev/kmsg
echo "Installing Alinux Linux. Please wait..." | tee /dev/kmsg
echo "=================================" | tee /dev/kmsg

modprobe -a sdhci-of-dwcmshc mlxbf_tmfifo mlxbf_gige pinctrl-mlxbf3 8021q vitesse dw_mmc_bluefield mmc_block virtio_console nvme mlxbf-bootctl 2>&1 | tee /dev/kmsg
modprobe -a mlx5_ib mlxfw ib_umad 2>&1 | tee /dev/kmsg

sleep 5

/bin/sh /alinux/install.sh
if [ \$? -eq 0 ]; then
        echo "===================================" | tee /dev/kmsg
        echo "Installation finished. Rebooting..." | tee /dev/kmsg
        echo "===================================" | tee /dev/kmsg
        echo
        sleep 3
        reboot -f
else
        echo "========================" | tee /dev/kmsg
        echo "Failed to install Alinux Linux" | tee /dev/kmsg
        echo "========================" | tee /dev/kmsg
fi
EOF

chmod +x scripts/initrd-install

cat > usr/lib/systemd/system/install-alinux.service << EOF
[Unit]
Description=Install Alinux Linux
After=initrd-root-fs.target initrd-parse-etc.service
After=dracut-initqueue.service dracut-mount.service

[Service]
Type=oneshot
ExecStart=/scripts/initrd-install
StandardInput=null
StandardOutput=syslog
StandardError=syslog+console
EOF

ln -s /usr/lib/systemd/system/install-alinux.service etc/systemd/system/initrd.target.wants/install-alinux.service

# Make initramfs
find . | cpio -H newc -o | gzip -9 > $initramfs

cd ..

mkdir -p /workspace

# BF4: ISO 9660 image
MLNX_REL=$(cat /etc/mlnx-release)

# possible redundant "_bf4" in MLNX_REL
# bf4-os-doca-bundle-3.3.0-409_26.01_alinux-4_bf4.iso -> bf4-os-doca-bundle-3.3.0-409_26.01_alinux-4.iso
MLNX_REL=$(echo $MLNX_REL | sed s/_bf4//)

ISO_FILENAME=$MLNX_REL".iso"

ISO_DIR=/workspace/iso
mkdir -p $ISO_DIR

# fonts
mkdir -p $ISO_DIR/boot/grub2/fonts
cp /boot/grub2/fonts/*.pf2 $ISO_DIR/boot/grub2/fonts

# *.mod files, e.g.: http.mod
# Optional: bootaa64.efi (gcdaa64.efi) is a self-contained grub cd image and the
# grub.cfg below only uses built-in commands, so a missing grub2-efi-aa64-modules
# must not fail the ISO.
if ls /usr/lib/grub/arm64-efi/*.mod > /dev/null 2>&1; then
	mkdir -p $ISO_DIR/boot/grub2/arm64-efi
	cp -r /usr/lib/grub/arm64-efi/*.mod $ISO_DIR/boot/grub2/arm64-efi
fi

# FAT ESP image file on ISO 9660 (mtools: no loop mount; works when /dev/loop* is unavailable, e.g. Docker)
dd if=/dev/zero of=efi.img bs=1M count=4
mkfs.vfat -F 12 efi.img -n "ESP"
mmd -i efi.img ::/efi
mmd -i efi.img ::/efi/boot
mcopy -i efi.img /boot/efi/EFI/*/gcdaa64.efi ::/efi/boot/bootaa64.efi

# bootaa64.efi: the EFI firmware used in boot sequence
# default: /EFI/BOOT/grub.cfg on the ISO9660 tree (see below)

mkdir -p $ISO_DIR/EFI/BOOT
cat > $ISO_DIR/EFI/BOOT/grub.cfg << EOF
loadfont unicode

set menu_color_normal=white/black
set menu_color_highlight=black/light-gray

set default=0
set timeout=3

menuentry "${MLNX_REL} installation" {
linux /boot/vmlinuz net.ifnames=0 keep_bootcon biosdevname=0 ip=dhcp
initrd /boot/initramfs
}
EOF

# Some firmware (incl. BlueField) loads \EFI\BOOT\BOOTAA64.EFI from the iso9660
# filesystem directly instead of the appended ESP, so place the bootloader there too.
cp /boot/efi/EFI/*/gcdaa64.efi $ISO_DIR/EFI/BOOT/BOOTAA64.EFI

cp /boot/vmlinuz-$kernel $ISO_DIR/boot/vmlinuz
cp $initramfs $ISO_DIR/boot/initramfs

mkdir -p $ISO_DIR/.disk
echo "$ISO_FILENAME" > $ISO_DIR/.disk/info

xorriso -as mkisofs \
-iso-level 3 \
-allow-lowercase \
-volid "BF_BUNDLE_ISO" \
-J \
-joliet-long \
-l \
-c boot/boot.cat \
-partition_offset 16 \
-append_partition 2 0xef efi.img \
-e --interval:appended_partition_2:all:: \
-no-emul-boot \
-partition_cyl_align all \
$ISO_DIR \
-output /workspace/$ISO_FILENAME

echo "ISO is ready: $(readlink -f /workspace/${ISO_FILENAME})"
