#!/bin/bash -ex
###############################################################################
#
# Copyright 2022 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################

cd ${0%*/*}

if [ ! -e Dockerfile ]; then
	echo "ERROR: Dockerfile is missing."
	exit 1
fi

if ! (which wget > /dev/null 2>&1); then
	echo "wget is required to build BFB"
	exit 1
fi

if ! (which docker > /dev/null 2>&1); then
	echo "docker is required to build BFB"
	exit 1
fi

DISTRO="bclinux"
DISTRO_VERSION="21.10"
DOCA_VERSION="1.5.1010"
MLNX_OFED_VERSION=5.8-2.0.6.0
BF_RELEASE="3.9.5-12666"
IMAGE_TYPE=${IMAGE_TYPE:-"prod"}

WDIR=/tmp/${DISTRO}${DISTRO_VERSION}.$$

if [ ! -e license ]; then
	echo "ERROR: license file is missing"
	exit 1
fi

mkdir -p $WDIR

mkdir -p $WDIR/bootimages
wget -P $WDIR/bootimages -r --no-verbose --no-directories -l1 --no-parent -A 'mlxbf-bootimages*.aarch64*.rpm' https://linux.mellanox.com/public/repo/bluefield/${BF_RELEASE}/bootimages/${IMAGE_TYPE}/


cp	Dockerfile \
	create_bfb \
	install.sh \
	license \
	../../common/tools/qemu-aarch64-static \
	build_bclinux_bfb \
        $WDIR

cd $WDIR

docker_image=bfb_runtime_${DISTRO,,}${DISTRO_VERSION,,}

docker rm -f BlueField_OS_${DISTRO}_${DISTRO_VERSION} 2> /dev/null || true

sed -i -e "s/@IMAGE_TYPE@/$IMAGE_TYPE/g;s/@CUSTOM_VERSION@/$CUSTOM_VERSION/g" \
        -e "s/@DOCA_VERSION@/$DOCA_VERSION/g" \
        -e "s/@MLNX_OFED_VERSION@/$MLNX_OFED_VERSION/g" \
        -e "s/@BF_RELEASE@/$BF_RELEASE/g" \
        -e "s/@DISTRO_VERSION@/$DISTRO_VERSION/g" build_bclinux_bfb

docker build -t ${docker_image} -f Dockerfile .
docker run -t --rm --privileged -e container=docker \
	-v $PWD:/workspace \
	--name BlueField_OS_${DISTRO}_${DISTRO_VERSION} \
	--mount type=bind,source=/dev,target=/dev \
	--mount type=bind,source=/sys,target=/sys \
	${docker_image}

readlink -f *.bfb

echo "Default root password is: bclinux"
