#!/bin/bash -e

cd ${0%*/*}

if [ ! -e Dockerfile ]; then
	echo "ERROR: Dockerfile is missing."
	exit 1
fi

if ! (which wget > /dev/null 2>&1); then
	echo "wget is required to build BFB"
	exit 1
fi

if ! (which docker > /dev/null 2>&1); then
	echo "docker is required to build BFB"
	exit 1
fi

DISTRO="debian"
DISTRO_VERSION="11"
VERSION="3.9.2"
DOCA_VERSION="1.4.0"

IMAGE_TYPE=${IMAGE_TYPE:-"prod"}

WDIR=/tmp/${DISTRO}${DISTRO_VERSION}.$$

mkdir -p $WDIR
wget -P $WDIR https://linux.mellanox.com/public/repo/bluefield/${VERSION}/bootimages/${IMAGE_TYPE}/mlxbf-bootimages_3.9.2-12271_arm64.deb
wget -P $WDIR -r --no-verbose --no-directories -l1 --no-parent -A 'doca-repo-aarch64-debian11-local_*_arm64.deb' https://linux.mellanox.com/public/repo/doca/${DOCA_VERSION}/${DISTRO}${DISTRO_VERSION}/aarch64/
mv $WDIR/doca-repo-aarch64-debian11-local_*_arm64.deb $WDIR/doca-repo.deb

cp	Dockerfile \
	create_bfb \
	install.sh \
	grubaa64.efi \
	../../common/tools/qemu-aarch64-static \
	$WDIR

cd $WDIR

docker build -t bfb_runtime_${DISTRO}${DISTRO_VERSION} -f Dockerfile .
docker run -t --rm --privileged -e container=docker \
	-v $PWD:/workspace \
	--name BlueField_OS_${DISTRO}_${DISTRO_VERSION} \
	--mount type=bind,source=/dev,target=/dev \
	--mount type=bind,source=/sys,target=/sys \
	--mount type=bind,source=/proc,target=/proc \
	bfb_runtime_${DISTRO}${DISTRO_VERSION}

readlink -f *.bfb

echo "Default root password is: debian"
