#!/bin/bash -x

###############################################################################
#
# Copyright 2022 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################

DOCA_VERSION=@DOCA_VERSION@
BSP_VERSION=@BSP_VERSION@
MLNX_OFED_VERSION=@MLNX_OFED_VERSION@
BASE_URL=@BASE_URL@
WDIR=${WDIR:-/tmp}

# Execute command w/ echo and exit if it fail
ex()
{
	echo "$@"
	if ! "$@"; then
		printf "\nFailed executing $@\n\n"
		exit 1
	fi
}

# Upgrade kernel
dnf update --nogpgcheck -y kernel-core kernel kernel-modules kernel-devel kernel-headers kernel-cross-headers kernel-modules-extra

kernel=`/bin/ls -1tr /lib/modules | tail -1`

dnf install -y \
	NetworkManager \
	grub2-tools grub2 grubby grub2-tools-minimal grub2-efi-aa64 grub2-efi-aa64-modules grub2-common grub2-tools-extra \
	efibootmgr tcpdump nvme-cli rsync binutils sg3_utils libnl3 bison flex meson libmnl libnuma perl lsof \
	python-netifaces libreswan python36 python36-devel python36-idle python36-libs python36-test python36-tkinter python36-Cython \
	device-mapper-persistent-data lvm2 acpid perf popt-devel bc edac-utils lm_sensors lm_sensors-sensord re2c ninja-build \
	cryptsetup rasdaemon pciutils-devel watchdog python3-sphinx python36-six kexec-tools jq python3-pip libnghttp2 wget sudo uriparser || true

# Set python2.7 as a default
update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
update-alternatives --install /usr/bin/python python /usr/bin/python2.7 10

mkdir -p $WDIR
cd $WDIR

# Build and install MLNX_OFED drivers
ex wget --quiet ${BASE_URL}/bluefield/${BSP_VERSION}/extras/mlnx_ofed/${MLNX_OFED_VERSION}/MLNX_OFED_SRC-${MLNX_OFED_VERSION}.tgz
ex tar xzf MLNX_OFED_SRC-${MLNX_OFED_VERSION}.tgz
ex MLNX_OFED_SRC-${MLNX_OFED_VERSION}/install.pl -k $kernel --kernel-extra-args '--with-sf-cfg-drv --without-xdp --without-odp' --kernel-only --disable-kmp

# find MLNX_OFED_SRC-${MLNX_OFED_VERSION}/RPMS -name '*rpm' -a ! -name '*debuginfo*rpm' -exec rpm -ihv '{}' \;

# Build and install BlueField SoC drivers
ex wget --quiet -r -np -nH --cut-dirs=3 -R "index.html*" ${BASE_URL}/bluefield/${BSP_VERSION}/extras/SRPMS/
mkdir -p ${WDIR}/${BSP_VERSION}/extras/{SPECS,RPMS,SOURCES,BUILD}

for p in ${WDIR}/${BSP_VERSION}/extras/SRPMS/*.src.rpm
do
	case $p in
		*rshim* | *libpka* | *mlx-OpenIPMI* | *mlxbf-bootctl*)
			continue
			;;
	esac
	ex rpmbuild --rebuild -D "debug_package %{nil}" -D "KVERSION $kernel" --define "KMP 0" --define "_topdir ${WDIR}/${BSP_VERSION}/extras" $p
done

ex rpm -ivh --force ${WDIR}/${BSP_VERSION}/extras/RPMS/aarch64/*.rpm

ex yum-config-manager --nogpgcheck --add-repo ${BASE_URL}/doca/${DOCA_VERSION}/rockylinux8.6/aarch64/

ex yum install --nogpgcheck -y doca-runtime-user doca-devel

ex rpm -e --nodeps $(rpm -qa mlxbf-bootimages*)
ex rpm -ihv --force /root/workspace/bootimages/mlxbf-bootimages*.aarch64.rpm

/usr/sbin/update-pciids || true

ex /root/workspace/create_bfb -k $kernel
