#!/bin/bash -x

###############################################################################
#
# Copyright 2023 NVIDIA Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
###############################################################################

set -e

LANG=C
SDIR="/root/workspace"
kernel=$(/bin/ls -1 /lib/modules/ | head -1)

WDIR=${WDIR:-/root/workspace/bfb}

echo "Work directory: $WDIR"

PATH=$PATH:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/mellanox/scripts:/opt/mellanox/scripts/bin
/bin/rm -rf ${WDIR}
mkdir -p ${WDIR}
cd ${WDIR}
/bin/rm -rf initramfs

initramfs=$WDIR/dump-initramfs-v0
kmods=""
for kmod in dw_mmc-bluefield dw_mmc dw_mmc-pltfm mmc_block mlxbf-bootctl \
			virtio_net virtio_console sdhci dw_mmc-pltfm sdhci-of-dwcmshc \
			xfs vfat  mlxbf-tmfifo mlx5_core mlx5_ib ib_umad nvme nvme-tcp \
			nvme-rdma nvme-fc nvme-fabrics nvme-core gpio-mlxbf3 mlxbf_gige
do
    if (modinfo -k $kernel $kmod 2>/dev/null | grep "filename:" | grep -q builtin); then
        continue
    fi

    mod=$(find /lib/modules/$kernel -name "${kmod}.ko*" 2> /dev/null || true)
    if [ -n "$mod" ]; then
        kmods="$kmods $kmod"
    fi
done
# Create ssh keys
yes | /usr/bin/ssh-keygen -A  -N ""
mkdir -p /root/.ssh
chmod 0700 /root/.ssh
touch /root/.ssh/authorized_keys
chmod 600 /root/.ssh/authorized_keys
echo "Building initramfs with: $kmods"
dracut --no-hostonly -m "bash network base systemd systemd-initrd dracut-systemd shutdown sshd ssh-client udev-rules" \
		--install "/usr/lib/udev/rules.d/91-tmfifo_net.rules /lib/udev/rules.d/92-oob_net.rules" \
		--force-drivers "$kmods" --gzip $initramfs ${kernel}
if [ $? -ne 0 ]; then
	echo "ERROR: dracut failed"
	exit 1
fi

cat > /etc/default/grub << EOF
GRUB_TIMEOUT=0
GRUB_RECORDFAIL_TIMEOUT=2
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL=console
GRUB_SERIAL_COMMAND="serial --unit=1"
GRUB_CMDLINE_LINUX="crashkernel=auto console=hvc0 console=ttyAMA0 earlycon=pl011,0x01000000 biosdevname=0"
GRUB_DISABLE_RECOVERY="true"
GRUB_TIMEOUT_STYLE=countdown
GRUB_DISABLE_OS_PROBER=false
GRUB_DISABLE_LINUX_UUID=false
EOF


case "$(file --brief --mime-type "$initramfs")" in
    "application/x-lzma")
        cat_initrd="lzcat" ;;
    "application/x-lz4")
        cat_initrd="lz4cat" ;;
    *)
        cat_initrd="zcat" ;;
esac

echo "Rebuilding $initramfs"

mkdir -p ${WDIR}/initramfs
cd initramfs
$cat_initrd "$initramfs" | cpio -i

copy_bin()
{
    if [ -e $1 ]; then
        bin=$1
    else
        bin=$(which $1 2> /dev/null)
    fi
    if [ -z "$bin" ]; then
        echo "ERROR: Cannot find $1"
        return 1
    fi
    mkdir -p .$(dirname $bin)
    if [ -e .${bin} ]; then
        /bin/rm -f .${bin}
    fi
    cp -a $bin .${bin}

    # Copy dependencies
    for lib in $(ldd $bin 2> /dev/null | grep '=>' | awk '{print $3}' | grep -v '(0x0')
    do
        if [ -e .$lib ]; then
            continue
        fi
        mkdir -p .$(dirname $lib)
        cp -a $lib .$lib
        if [ -h $lib ]; then
            tlib=$(readlink -f $lib)
            if [ ! -e .$tlib ]; then
                mkdir -p .$(dirname $tlib)
                cp $tlib .$tlib
            fi
        fi
    done
}

copy_rpm()
{
    package=$1

    if ! (rpm -q $package); then
        yum install -y $package || return
    fi

    case $package in
        chkconfig)
            for f in $(rpm -ql $package | grep -v share)
            do
                if [ -d $f ]; then
                    mkdir -p .${f}
                else
                    copy_bin $f
                fi
            done
            ;;
        *mft*|mstflint)
            for f in $(rpm -ql $package | grep -vw man)
            do
                if [ -d $f ]; then
                    continue
                fi
                copy_bin $f
            done
            ;;
        *)
            for f in $(rpm -ql $package | grep -vE 'share|build-id')
            do
                if [ -d $f ]; then
                    continue
                fi
                copy_bin $f
            done
            ;;
    esac
}

# Copy the content of RPM packages
for package in gawk mlxbf-bfscripts mlxbf-bootctl util-linux dosfstools \
			   e2fsprogs kmod pciutils usbutils chkconfig mstflint mft \
			   mft-oem mft-mlx5 mft-nvredfish $kernel_mft tar xfsprogs coreutils parted which curl \
			   openssl net-tools wget dhcp-client ipcalc iputils dbus-tools \
			   systemd-udev initscripts shadow-utils crypto-policies \
			   openssh openssh-server rng-tools passwd dmidecode \
			   python36 sshpass $ADDON_RPMS
do
    copy_rpm $package || true
done

# Copy tools
for tool in	xz efibootmgr bash getopt hexdump lspci perl \
		lsblk shutdown systemctl strings \
		id grep hostnamectl $ADDON_TOOLS
do
    if [ -d $tool ]; then
        continue
    fi
    copy_bin $tool
done

depmod -a -b ./ $kernel
ldconfig -r ./
mkdir -p usr/share/hwdata/ bin/
cp /usr/share/hwdata/pci.ids ./usr/share/hwdata/
[ -d /lib/firmware/swissbit/ ] && cp -a /lib/firmware/swissbit/ ./lib/firmware/

mkdir -p mnt

if [ -e /usr/bin/pkexec ]; then
    # CVE-2021-4034 workaround
    chmod 0755 /usr/bin/pkexec
fi

# Remove hostname that includes docker container's id
/bin/rm -f ./etc/hostname
echo localhost > /etc/hostname



mkdir -p ol
# Tar the image
XZ_OPT="--threads=0 -9 --verbose" tar -cJp --exclude='./workspace' --exclude='./signing-local' --exclude='./signing-shared' --exclude='./var/run/docker.sock' \
 --exclude='./root/workspace' --exclude='./tmp/*' --exclude='./run/*' --exclude='./sys/*' --exclude='./proc/*' --exclude='./dev/*' --exclude='./.dockerenv' \
 --exclude='./root/rpmbuild' --exclude='./root/.rpmmacros' --exclude='./root/.bash_history' --exclude='./var/tmp/*rpm' --exclude='./bin/qemu-aarch64-static' \
 --exclude='./usr/bin/qemu-aarch64-static' --exclude='./usr/bin/qemu-arm-static' --exclude='./var/lib/yum/*' --exclude='./var/cache/yum/*' -f "./ol/image.tar.xz" -C / .
install -m 0755 ${SDIR}/install.sh ./ol/install.sh
cp -a ${SDIR}/install.env ./ol/

mkdir scripts
cat > scripts/initrd-install << EOF
#!/bin/sh

echo
echo "=================================" | tee /dev/kmsg
echo "Installing OL Linux. Please wait..." | tee /dev/kmsg
echo "=================================" | tee /dev/kmsg


for kmod in $kmods
do
	/sbin/modprobe \$kmod 2>&1 | tee /dev/kmsg
done

sleep 5

/bin/sh /ol/install.sh
if [ \$? -eq 0 ]; then
        echo "===================================" | tee /dev/kmsg
        echo "Installation finished. Rebooting..." | tee /dev/kmsg
        echo "===================================" | tee /dev/kmsg
        echo
        sleep 3
        reboot -f
else
        echo "========================" | tee /dev/kmsg
        echo "Failed to install OL Linux" | tee /dev/kmsg
        echo "========================" | tee /dev/kmsg
fi
EOF

chmod +x scripts/initrd-install

ln -s /usr/lib/systemd/system/sshd.service etc/systemd/system/initrd.target.wants/sshd.service

cat > usr/lib/systemd/system/install-ol.service << EOF
[Unit]
Description=Install OL Linux
After=initrd-root-fs.target initrd-parse-etc.service
After=dracut-initqueue.service dracut-mount.service

[Service]
Type=oneshot
ExecStart=/scripts/initrd-install
StandardInput=null
StandardOutput=syslog
StandardError=syslog+console
EOF

ln -s /usr/lib/systemd/system/install-ol.service etc/systemd/system/initrd.target.wants/install-ol.service

# Make initramfs
find . | cpio -H newc -o | gzip -9 > $initramfs

cd ..

mkdir -p /workspace

# BF4: ISO 9660 image
MLNX_REL=$(cat /etc/mlnx-release)

# possible redundant "_bf4" in MLNX_REL
# bf4-os-doca-bundle-3.3.0-409_26.01_oraclelinux-9_bf4.iso -> bf4-os-doca-bundle-3.3.0-409_26.01_oraclelinux-9.iso
MLNX_REL=$(echo $MLNX_REL | sed s/_bf4//)

ISO_FILENAME=$MLNX_REL".iso"

ISO_DIR=/workspace/iso
mkdir -p $ISO_DIR

# fonts
mkdir -p $ISO_DIR/boot/grub2/fonts
cp /boot/grub2/fonts/*.pf2 $ISO_DIR/boot/grub2/fonts

# *.mod files, e.g.: http.mod
mkdir -p $ISO_DIR/boot/grub2/arm64-efi
cp -r /usr/lib/grub/arm64-efi/*.mod $ISO_DIR/boot/grub2/arm64-efi

# FAT ESP image file on ISO 9660 (mtools: no loop mount; works when /dev/loop* is unavailable, e.g. Docker)
dd if=/dev/zero of=efi.img bs=1M count=4
mkfs.vfat -F 12 efi.img -n "ESP"
mmd -i efi.img ::/efi
mmd -i efi.img ::/efi/boot
mcopy -i efi.img /boot/efi/EFI/*/gcdaa64.efi ::/efi/boot/bootaa64.efi

# bootaa64.efi: the EFI firmware used in boot sequence
# default: /EFI/BOOT/grub.cfg on the ISO9660 tree (see below)

mkdir -p $ISO_DIR/EFI/BOOT
cat > $ISO_DIR/EFI/BOOT/grub.cfg << EOF
loadfont unicode

set menu_color_normal=white/black
set menu_color_highlight=black/light-gray

set default=0
set timeout=3

menuentry "${MLNX_REL} installation" {
linux /boot/vmlinuz net.ifnames=0 keep_bootcon biosdevname=0 ip=dhcp
initrd /boot/initramfs
}
EOF

cp /boot/vmlinuz-$kernel $ISO_DIR/boot/vmlinuz
cp $initramfs $ISO_DIR/boot/initramfs

mkdir -p $ISO_DIR/.disk
echo "$ISO_FILENAME" > $ISO_DIR/.disk/info

xorriso -as mkisofs \
-iso-level 3 \
-allow-lowercase \
-volid "BF_BUNDLE_ISO" \
-J \
-joliet-long \
-l \
-c boot/boot.cat \
-partition_offset 16 \
-append_partition 2 0xef efi.img \
-e --interval:appended_partition_2:all:: \
-no-emul-boot \
-partition_cyl_align all \
$ISO_DIR \
-output /workspace/$ISO_FILENAME

echo "ISO is ready: $(readlink -f /workspace/${ISO_FILENAME})"
